### ISSUE TITLE
Issue with Flux GGUF models

### ISSUE THREAD

**Issue by faustoserone** [Jelosus2/ImgMetadataConverter#1]
Hi,
tested with 2 models, same error

Model1:
[Error] [ImgMetadataConverter] Model flux1-dev-Q6_K.gguf has invalid metadata length 14064895815, aborting...

Model2:
[Error] [ImgMetadataConverter] Model flux-hyp8-Q4_0.gguf has invalid metadata length 14064895815, aborting...

**Comment by Jelosus2** [comment]
Gguf files don't work since they have different headers than safetensor files. I will update the code so it doesn't work with those kind of files. Civitai doesn't support raw gguf files anyways so not a big deal.

**Comment by faustoserone** [comment]
Thanks!
