### ISSUE TITLE
LiteDB issues? Metadata not being loaded correctly in Image History

### ISSUE THREAD

**Issue by yo1nkers** [Jelosus2/ImgMetadataConverter#4]
Loading up the Image History causes all image metadata to forcefully be accessed, and for some reason it's erroring. I've attempted to uninstall the extension, and the issue is now still present without the extension. I've made an issue https://github.com/mcmonkeyprojects/SwarmUI/issues/458 here but in the event it's related to the actual extension, I'll have this here

Essentially, using the extension for quite a while and things have been fine until today's SwarmUI update. I am experiencing an influx of new errors.

**Comment by yo1nkers** [comment]
https://pastebin.com/6W0XwPjn Attached is a large log because of character size limit

**Comment by Jelosus2** [comment]
Try to do what mcmonkey suggested because I'm not having any issues

**Comment by yo1nkers** [comment]
Although this is completed, I've found it's best to just never have images with meta produced after conversion in the same folders as regular Swarm folders as Swarm isn't built for them.

After I segregated all of the images with CivitAI-compliant metadata into their own folders away from the generation folder, these issues disappeared.
